kafka:
  brokers:
  group: triage

management:
  endpoints.web.exposure.include: health,prometheus

server:
  port:

spring:
  application.name: kafka-triage
  jackson:
    default-property-inclusion: always
  profiles.active: dev

---

spring.profiles: dev

kafka:
  brokers: 192.168.99.100:9092

logging.level:
  com.fasterxml.jackson: DEBUG
  org.apache.kafka.clients.consumer.KafkaConsumer: DEBUG
  org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: DEBUG
  org.apache.kafka.clients.consumer.internals.Fetcher: DEBUG
  org.apache.kafka.clients.producer.KafkaProducer: DEBUG
