management:
  endpoints.web.exposure.include: health,prometheus

server:
  port:

spring:
  application.name: kafka-triage
  data.web:
    pageable:
      default-page-size: 10
      max-page-size: 100
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
    separator: ';;'
  jackson:
    default-property-inclusion: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    ack-mode: record
    bootstrap-servers:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: triage
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      properties:
        linger.ms: 1
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  profiles.active:
