management:
  endpoints.web.exposure.include: health,prometheus

server:
  port:

spring:
  application.name: kafka-triage
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jackson:
    default-property-inclusion: always
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    ack-mode: record
    bootstrap-servers:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: triage
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      properties:
        linger.ms: 1
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  profiles.active:
